### ISSUE TITLE
Enable  "Manage node(s) with NCM" 

### ISSUE THREAD

**Issue by Andyjb8** [jeisenbath/ansible-collection-solarwinds-orion#11]
Is there a way I can  enable "Manage node(s) with NCM"?  It's a yes/no drop down when you add/edit a node in Solarwinds. I am not seeing any options under solarwinds.orion.orion_node or solarwinds.orion.orion_update_node to do this. Would this option be easy to add?

**Comment by jeisenbath** [comment]
If it can be done via API it can be done, it will just take some research. Likely, this belongs in its own module so that orion_node itself doesn't get too bloated with parameters, but it could be both. I'll mark this as an enhancement request, not sure when I'll be able to research it myself.

**Comment by jeisenbath** [comment]
Added a module "orion_node_ncm" in release 1.3.0 which can add or remove an existing node to NCM. That's the best I can do for NCM, I asked around my org and we aren't using NCM for me to test functionality outside of that.

**Comment by Andyjb8** [comment]
This works to say "yes" to "Manage node(s) with NCM" and it assigns the default global connection profile. This works for cisco devices but for juniper devices we have to use our juniper connection profile due to junipers not using enable to login. Is there a way this module can specify a pre-created ncm global connection profile?

**Comment by jeisenbath** [comment]
I looked into it today, it looks like maybe some combination of invoking GetAllConnectionProfiles on Cirrus.Nodes to get an ID for the connection profile, then using update on the Cirrus.Nodes uri to set the ConnectionProfile ID to that number would work. I can't find a method or table to get only one connection profile by name, so that's the best I can see. There's also other methods on Cirrus.Nodes like creating and deleting connection profiles. You're welcome to take a crack at it, otherwise it'll go on my road map.
