### ISSUE TITLE
Unable to specify solarwinds port

### ISSUE THREAD

**Issue by dgmyrs** [jeisenbath/ansible-collection-solarwinds-orion#18]
The Solarwinds api I work with runs on a custom port other than 17774.  I know the orionsdk python lib has a parameter to specify port, so hopefully it would be straight forward to add a port option to the auth parameters.

**Comment by jeisenbath** [comment]
That would be simple enough to add, you're correct there's already an option to pass through the SwisClient object. I have at least one other minor change and one documentation update to make hopefully today/next week, so I should be able to include that in the next release.

**Comment by jeisenbath** [comment]
Turns out, this is tricky because the port argument was added in orionsdk 0.4.0, and they also made the default API port 17774 in 0.4.0 instead of 17778 which is the 'legacy' port, but I can't say they exactly deprecated it with good warning. The code to update the collection is easy, but I'll need to bump up the major version since this will be a breaking change, so I might try to figure out putting that change on a 'devel' branch for a few months and put up a discussion thread so people can be aware.

**Comment by dgmyrs** [comment]
Ah, yeah, that does make it tricky.  Would it make sense to make the port optional, and if not supplied just leave it out of the call to SwisClient.  But if it is supplied, inspect SwisClient to see if it has the port argument, and if it does, use it.  Something like:

`
if 'port' in inspect.getfullargspec(orionsdk.SwisClient).args:
    # Use port
`

**Comment by jeisenbath** [comment]
I finally got the new branch up, tested only on ansible 2.16 and python 3.11. Both orionsdk 0.3.0 and 0.4.0 passed my module tests on both the new API at 17774 and legacy on 17778, would love it if you can test yourself and give feedback.  You can install this branch by running: ansible-galaxy collection install git+https://github.com/jeisenbath/ansible-collection-solarwinds-orion.git,devel-2.0 --force

**Comment by dgmyrs** [comment]
I tested it out on our legacy environment, with port 17778, and it works perfectly for the orion_node_info and orion_node module tests that I have.  Thanks!
